name: CI with CD
on:
  push:
    branches:
      - goshujin-sama
  release:
    types:
      - published
jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: meta
        uses: docker/metadata-action@v3
        with:
          images: myl7/tgchan2tw
          tags: |
            type=edge
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: Prepare deps
        run: bash scripts/setup-dep.sh gnu
      - name: Test
        run: bash scripts/test.sh
      - uses: docker/login-action@v1
        with:
          username: myl7
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
