name: CI with CD
on:
  push:
    branches:
      - goshujin-sama
jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: Test
        run: bash scripts/test.sh
      - uses: docker/login-action@v1
        with:
          username: myl7
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: myl7/tgchan2tw:latest
